name: CI

on:
  push:
    branches:
      - '**'

jobs:
  deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/deps

  build:
    needs: deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/deps
      - run: pnpm prod
      - uses: 'actions/upload-pages-artifact@v3'
        with:
          name: dist
          path: dist

  typecheck:
    needs: deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/deps
      - run: pnpm typecheck

  check:
    needs: deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/deps
      - run: pnpm check

  test:
    needs: deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/deps
      - run: pnpm test

  pass:
    runs-on: ubuntu-latest
    needs:
      - build
      - typecheck
      - check
      - test
    steps:
      - run: exit 0

  deploy:
    needs: pass
    if: contains(github.ref, 'main')
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: 'dist'

